<?xml version="1.0" encoding="UTF-8"?><testrun name="TestFibbIterator" project="BT-Library-Java" tests="5" started="4" failures="1" errors="0" ignored="0">
  <testsuite name="bt.tests.core.collections.iterators.TestFibbIterator" incomplete="true">
    <testcase name="test_CTOR_FibIterator_Fst_True" classname="bt.tests.core.collections.iterators.TestFibbIterator" time="0.0">
      <failure>junit.framework.AssertionFailedError&#13;
	at junit.framework.Assert.fail(Assert.java:55)&#13;
	at junit.framework.Assert.assertTrue(Assert.java:22)&#13;
	at junit.framework.Assert.assertTrue(Assert.java:31)&#13;
	at junit.framework.TestCase.assertTrue(TestCase.java:201)&#13;
	at bt.tests.core.collections.iterators.TestFibbIterator.test_CTOR_FibIterator_Fst_True(TestFibbIterator.java:34)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:176)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:141)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="test_ForLoopNext_Step2_True" classname="bt.tests.core.collections.iterators.TestFibbIterator" time="0.0"/>
    <testcase name="test_ForLoopPrevious_Step2_True" classname="bt.tests.core.collections.iterators.TestFibbIterator" time="0.001"/>
    <testcase name="test_WhileLoopNext_Step2_34" classname="bt.tests.core.collections.iterators.TestFibbIterator" incomplete="true"/>
    <testcase name="test_WhileLoopPrevious_Step2_True" classname="bt.tests.core.collections.iterators.TestFibbIterator" incomplete="true"/>
  </testsuite>
</testrun>
