<?xml version="1.0" encoding="UTF-8"?><testrun name="TestRatajListCopy" project="BT-Library-Java" tests="12" started="12" failures="3" errors="0" ignored="0">
  <testsuite name="bt.tests.core.collections.dataTypes.TestRatajListCopy" time="0.008">
    <testcase name="test_CTOR_1size_true" classname="bt.tests.core.collections.dataTypes.TestRatajListCopy" time="0.001"/>
    <testcase name="test_CTOR_null_true" classname="bt.tests.core.collections.dataTypes.TestRatajListCopy" time="0.0"/>
    <testcase name="test_add_On1size_Expect_size2" classname="bt.tests.core.collections.dataTypes.TestRatajListCopy" time="0.002">
      <failure>junit.framework.AssertionFailedError: expected:&lt;1&gt; but was:&lt;2&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:329)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:78)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:234)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:241)&#13;
	at junit.framework.TestCase.assertEquals(TestCase.java:409)&#13;
	at bt.tests.core.collections.dataTypes.TestRatajListCopy.test_add_On1size_Expect_size2(TestRatajListCopy.java:180)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:176)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:141)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="test_add_On2size_Expect_size3" classname="bt.tests.core.collections.dataTypes.TestRatajListCopy" time="0.001">
      <failure>junit.framework.AssertionFailedError: expected:&lt;2&gt; but was:&lt;3&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:329)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:78)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:234)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:241)&#13;
	at junit.framework.TestCase.assertEquals(TestCase.java:409)&#13;
	at bt.tests.core.collections.dataTypes.TestRatajListCopy.test_add_On2size_Expect_size3(TestRatajListCopy.java:197)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:176)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:141)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="test_add_On3size_Expect_size4" classname="bt.tests.core.collections.dataTypes.TestRatajListCopy" time="0.0">
      <failure>junit.framework.AssertionFailedError: expected:&lt;3&gt; but was:&lt;4&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:329)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:78)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:234)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:241)&#13;
	at junit.framework.TestCase.assertEquals(TestCase.java:409)&#13;
	at bt.tests.core.collections.dataTypes.TestRatajListCopy.test_add_On3size_Expect_size4(TestRatajListCopy.java:214)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:176)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:141)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="test_add_Onnull_Expect_size1" classname="bt.tests.core.collections.dataTypes.TestRatajListCopy" time="0.0"/>
    <testcase name="test_druk_1size_true" classname="bt.tests.core.collections.dataTypes.TestRatajListCopy" time="0.0"/>
    <testcase name="test_druk_3size_true" classname="bt.tests.core.collections.dataTypes.TestRatajListCopy" time="0.001"/>
    <testcase name="test_druk_null_true" classname="bt.tests.core.collections.dataTypes.TestRatajListCopy" time="0.0"/>
    <testcase name="test_maxVal_1size_true" classname="bt.tests.core.collections.dataTypes.TestRatajListCopy" time="0.0"/>
    <testcase name="test_maxVal_3size_true" classname="bt.tests.core.collections.dataTypes.TestRatajListCopy" time="0.0"/>
    <testcase name="test_maxVal_null_true" classname="bt.tests.core.collections.dataTypes.TestRatajListCopy" time="0.001"/>
  </testsuite>
</testrun>
